# Generated by Django 4.0.3 on 2022-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('golos', models.IntegerField()),
            ],
            options={
                'db_table': 'jogo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogoequipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jogoequipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogojogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jogojogador',
                'managed': False,
            },
        ),
    ]
