# Generated by Django 4.0.3 on 2022-03-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'equipa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jogadorequipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jogadorequipa',
                'managed': False,
            },
        ),
    ]
